name: Build and save my Docker image to a registry

on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: "ghcr.io"
  IMAGE_NAME: "todo-app"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_ACCESS_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ env.REG_NAME }}/${{ github.repository }}:${{ env.IMAGE_NAME }} .

      - name: Push Docker image to registry
        run: docker push ${{ env.REG_NAME }}/${{ github.repository }}:${{ env.IMAGE_NAME }}

